class Config:
    VIDEO_WIDTH = 640
    VIDEO_HEIGHT = 480
    FPS = 20
    CANVAS_WIDTH = VIDEO_WIDTH
    CANVAS_HEIGHT = VIDEO_HEIGHT
    BRUSH_SIZE_MIN = 1
    BRUSH_SIZE_MAX = 50
    BRUSH_SIZE_DEFAULT = 5
    DEFAULT_COLOR = "#FFFFFF"
    UNDO_STACK_SIZE = 50